# Generated by Django 5.2.7 on 2025-11-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camions',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
